spring:
  application:
    name: enginuity
  datasource:
    url: jdbc:mysql://localhost:3306/enginuity?createDatabaseIfNotExist=true
    username: root
    password: 21042003
  flyway:
    enabled:  true
    url: jdbc:mysql://localhost:3306/enginuity?createDatabaseIfNotExist=true
    user: root
    password: 21042003
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600000
    refreshTokenExpiration: 604800000
#    refreshTokenExpiration: 604800000
bunny:
  storage:
    zoneName: ielts-learning
    regionUrl: https://storage.bunnycdn.com
    accessKey: ${BUNNY_SECRET}
    pullZoneUrl: https://ielts-learning.b-cdn.net

openai:
  api:
    key: ${OPENAI_API_KEY}
  model: gpt-4-turbo
  maxTokens: 3000
  temperature: 0.4
  timeout: 300
