package com.codewithmosh.store.repositories;

import com.codewithmosh.store.entities.WritingExercise;
import com.codewithmosh.store.entities.enums.CreationSource;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;
import java.util.Optional;

/**
 * Author: lamlevungan
 * Date: 27/04/2025
 **/
public interface WritingExerciseRepository extends JpaRepository<WritingExercise, Long> {

    // Query to get all exercises by a specific user (user_created), ai_generated by the user, or system_uploaded
    @Query("SELECT we FROM WritingExercise we " +
            "WHERE (we.user.id = :userId AND we.creationSource IN (:userCreated, :aiGenerated)) " +
            "OR we.creationSource = :systemUploaded")
    List<WritingExercise> findAllByUserIdAndCreationSource(
            Long userId,
            CreationSource userCreated,
            CreationSource aiGenerated,
            CreationSource systemUploaded);

    Optional<WritingExercise> findById(Long id);

    // Find by id, and check userId if creationSource is user_created or ai_generated
    @Query("SELECT we FROM WritingExercise we " +
            "WHERE we.id = :id AND (" +
            "(we.creationSource = :userCreated AND we.user.id = :userId) " +
            "OR (we.creationSource = :aiGenerated AND we.user.id = :userId) " +
            "OR we.creationSource = :systemUploaded)")
    Optional<WritingExercise> findByIdAndUserId(
            Long id,
            Long userId,
            CreationSource userCreated,
            CreationSource aiGenerated,
            CreationSource systemUploaded);
}
